spring.config.import=optional:file:.env[.properties]

spring.application.name=facilio-campus

# ===============================
# DATABASE CONFIGURATION (NEON)
# ===============================
# We are using an environment variable DB_URL so you don't commit your password to GitHub!
# The default fallback (after the colon) is a placeholder. 
# You should set the DB_URL variable on your machine.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE SETTINGS
# ===============================
# 'update' automatically builds your database tables based on your Java code
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the terminal for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Web server
server.port=${SERVER_PORT:8089}
